# Basic cloudflared config.yaml for openwrt
#
# You will also need at least some of the following packages
# opkg install cloudflared coreutils-base64 curl luci-app-cloudflared nano-full wget
#
# You also need to generated a client auth certificate by doing the following:
# cloudflared tunnel login
#
# Running the above will create a link you can open and allow the access
#
# Then you just need to: mv /root/.cloudflared/cert.pem /etc/cloudflared/cert.pem
#
# Then go into OpenWRT's webUI and pointy clicky to set everything else up
#

tunnel: <tunnelid>
credentials-file: /etc/cloudflared/<tunnelid>.json
protocol: http2
